# Generated by Django 3.1.7 on 2021-07-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing_address',
            options={'verbose_name': 'Billing_Address', 'verbose_name_plural': 'Billing_Addresses'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='shop.Category'),
        ),
    ]
