# Generated by Django 3.1.3 on 2020-11-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201121_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.billing_address'),
        ),
    ]
