# Generated by Django 3.1.3 on 2021-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
