# Generated by Django 3.1.7 on 2021-07-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210127_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
